### ISSUE TITLE
Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

### ISSUE THREAD

**Issue by jcubic** [raimohanska/ourboard#180]
It seems that this project doesn't work at all for me.

Browser Chrome, Fedora GNU/Linux.

![board](https://user-images.githubusercontent.com/280241/137643023-59cef73a-d6d7-4746-9c87-69cd81e2af3d.png)

Not even a single board works, I was testing the default one here.

Maybe it's a hacker news effect.

**Comment by raimohanska** [comment]
There's indeed something wrong with the "default" board. Will see into that. 

If you create a new board from the front page, it should work fine.

**Comment by raimohanska** [comment]
I reseted the default shared board.

**Comment by raimohanska** [comment]
Took database backup `b013` before reset.

**Comment by raimohanska** [comment]
From the logs:

 Oct 17 13:44:53 r-board app/web.1 Loading board default into memory
Oct 17 13:44:53 r-board app/web.1 Serial skip 4553 -> 4610
Oct 17 13:44:53 r-board app/web.1 Moving unknown item 26d10c97-1cc5-4ccb-aa0a-07fc69248c78
Oct 17 13:44:53 r-board app/web.1 /app/common/src/domain.ts:476
Oct 17 13:44:53 r-board app/web.1     if (!item) throw Error("Item not found: " + id)
Oct 17 13:44:53 r-board app/web.1                      ^
Oct 17 13:44:53 r-board app/web.1 Error: Item not found: 26d10c97-1cc5-4ccb-aa0a-07fc69248c78
Oct 17 13:44:53 r-board app/web.1     at null.<anonymous> (/app/common/src/domain.ts:476:22)
Oct 17 13:44:53 r-board app/web.1     at null.<anonymous> (/app/common/src/board-reducer.ts:160:52)
Oct 17 13:44:53 r-board app/web.1     at Array.map (<anonymous>)
Oct 17 13:44:53 r-board app/web.1     at Object.boardReducer (/app/common/src/board-reducer.ts:159:40)
Oct 17 13:44:53 r-board app/web.1     at null.<anonymous> (/app/backend/src/board-store.ts:45:48)
Oct 17 13:44:53 r-board app/web.1     at Array.reduce (<anonymous>)
Oct 17 13:44:53 r-board app/web.1     at null.updateBoardWithEventChunk (/app/backend/src/board-store.ts:45:31)
Oct 17 13:44:53 r-board app/web.1     at null.<anonymous> (/app/backend/src/board-store.ts:190:17)
Oct 17 13:44:53 r-board app/web.1     at QueryStream.<anonymous> (/app/backend/src/board-store.ts:147:17)
Oct 17 13:44:53 r-board app/web.1     at QueryStream.emit (node:events:369:20)
Oct 17 13:44:53 r-board app/web.1 Item not found: 26d10c97-1cc5-4ccb-aa0a-07fc69248c78
Oct 17 13:44:53 r-board app/web.1 Error fetching board history for snapshot update for board default. Rebooting snapshot...
Oct 17 13:44:53 r-board app/web.1 Serial skip 4553 -> 4610
Oct 17 13:44:53 r-board app/web.1 Moving unknown item 4a425b8b-f3ca-4868-b69e-f392d5236c7f
Oct 17 13:44:53 r-board app/web.1 /app/common/src/domain.ts:476
Oct 17 13:44:53 r-board app/web.1     if (!item) throw Error("Item not found: " + id)
Oct 17 13:44:53 r-board app/web.1                      ^
Oct 17 13:44:53 r-board app/web.1 Error: Item not found: 4a425b8b-f3ca-4868-b69e-f392d5236c7f
Oct 17 13:44:53 r-board app/web.1     at null.<anonymous> (/app/common/src/domain.ts:476:22)
Oct 17 13:44:53 r-board app/web.1     at null.<anonymous> (/app/common/src/board-reducer.ts:160:52)
Oct 17 13:44:53 r-board app/web.1     at Array.map (<anonymous>)
Oct 17 13:44:53 r-board app/web.1     at Object.boardReducer (/app/common/src/board-reducer.ts:159:40)
Oct 17 13:44:53 r-board app/web.1     at null.<anonymous> (/app/backend/src/board-store.ts:45:48)
Oct 17 13:44:53 r-board app/web.1     at Array.reduce (<anonymous>)
Oct 17 13:44:53 r-board app/web.1     at null.updateBoardWithEventChunk (/app/backend/src/board-store.ts:45:31)
Oct 17 13:44:53 r-board app/web.1     at QueryStream.<anonymous> (/app/backend/src/board-store.ts:147:17)
Oct 17 13:44:53 r-board app/web.1     at QueryStream.emit (node:events:369:20)
Oct 17 13:44:53 r-board app/web.1     at QueryStream.emit (node:domain:470:12)
Oct 17 13:44:53 r-board app/web.1 Board load failed for board default. Running compact/fix.
Oct 17 13:44:54 r-board app/web.1 History discontinuity: 0 -> 4610 for board default
Oct 17 13:44:54 r-board app/web.1 Aborting compaction of board default due to inconsistent history
Oct 17 13:44:54 r-board app/web.1 Found snapshot at serial 4553
Oct 17 13:44:54 r-board app/web.1 Cannot find a consecutive event for snapshot. First event is 4610
Oct 17 13:44:54 r-board app/web.1 Error while handling event from client. Closing connection. /app/common/src/domain.ts:476
Oct 17 13:44:54 r-board app/web.1     if (!item) throw Error("Item not found: " + id)
Oct 17 13:44:54 r-board app/web.1                      ^
Oct 17 13:44:54 r-board app/web.1 Error: Item not found: 4a425b8b-f3ca-4868-b69e-f392d5236c7f
Oct 17 13:44:54 r-board app/web.1     at null.<anonymous> (/app/common/src/domain.ts:476:22)
Oct 17 13:44:54 r-board app/web.1     at null.<anonymous> (/app/common/src/board-reducer.ts:160:52)
Oct 17 13:44:54 r-board app/web.1     at Array.map (<anonymous>)
Oct 17 13:44:54 r-board app/web.1     at Object.boardReducer (/app/common/src/board-reducer.ts:159:40)
Oct 17 13:44:54 r-board app/web.1     at null.<anonymous> (/app/backend/src/board-store.ts:45:48)
Oct 17 13:44:54 r-board app/web.1     at Array.reduce (<anonymous>)
Oct 17 13:44:54 r-board app/web.1     at null.updateBoardWithEventChunk (/app/backend/src/board-store.ts:45:31)
Oct 17 13:44:54 r-board app/web.1     at QueryStream.<anonymous> (/app/backend/src/board-store.ts:147:17)
Oct 17 13:44:54 r-board app/web.1     at QueryStream.emit (node:events:369:20)
Oct 17 13:44:54 r-board app/web.1     at QueryStream.emit (node:domain:470:12)

**Comment by raimohanska** [comment]
Because of the limited log retention we have on Heroku, I cannot get to see the logs for the time when things started to go wrong. Based on the aftermatch pictured in the log it seems that some events are missing from the database.

**Comment by jcubic** [comment]
It works now thanks. It's a great project.
